obfuscation example
Lost-Hex/licensespring-obfuscation pull request #1
Opened 2023-04-06 10:58 UTC by MIOCIC

2023-04-06 11:15 UTC, Smthng0 requested changes

2023-04-06 11:15 UTC, Smthng0 commented on .gitignore
> +**/.DS_Store
this is double, it's enought to use just one (.DS_Store)

2023-04-06 11:15 UTC, Smthng0 commented on README.md
> +            MyLicenseManager liscenceManagerClass = new MyLicenseManager();
you're missing the MyLicenseManager class -> not sure if the app will work at all

2023-04-06 11:15 UTC, Smthng0 commented on README.md
> +This will generate a JAR file with dependencies and obfuscate the code using ProGuard. The resulting JAR file will be located in the `target` directory.
put an empty new line after this so the images is in a new line (currently it's wapped around the text)
<img width="229" alt="image" src="https://user-images.githubusercontent.com/33116911/230359636-b0111af3-1898-418a-977c-ed7dcc88cfc3.png">

2023-04-06 11:15 UTC, Smthng0 commented on README.md
> +Picture below shows side-by-side comparison of LicenseManagerClass before and after obfuscation.
same here, new line after the text so image is seperated

2023-04-06 11:15 UTC, Smthng0 commented on README.md
> +The `App` class is the main entry point of the application. It expects five command-line arguments: `apiKey`, `sharedKey`, `licenceKey`, `productName`, and `isStaging` (yes/no).
mention that they need to be in the exact order, it's important info

2023-04-06 11:15 UTC, Smthng0 commented on README.md
> +The `App` class is the main entry point of the application. It expects five command-line arguments: `apiKey`, `sharedKey`, `licenceKey`, `productName`, and `isStaging` (yes/no).
you can deafult "isStaging" param to "no" in case it's not part of the input arguments -> this will make it an optional param (which it should be)

2023-04-06 11:15 UTC, Smthng0 commented on img.png
put the images in a folder, not the project root (like /example-images)

and use a more descriptive name for images (like jar_comparison or whatever the image is showing)

2023-04-06 11:15 UTC, Smthng0 commented on img_1.png
same as the image above

2023-04-06 11:15 UTC, Smthng0 commented on pom.xml
> +      <version>2.4.5</version>
change this to the latest version (you can find it in the docs)

2023-04-06 11:15 UTC, Smthng0 commented on src/test/java/com/losthex/AppTest.java
the whole test is a JUnit 3 test case

remove the file and create a new test for JUnit 4 (which is added as a dependancy)

2023-04-06 11:17 UTC, Smthng0 commented
also add a description about the pull request to the summary -> brief explanation what is this PR about

<img width="942" alt="image" src="https://user-images.githubusercontent.com/33116911/230361687-46ac1cfd-5207-4a56-8308-bd5731327f81.png">

2023-04-07 08:59 UTC, Smthng0 requested changes, later dismissed

2023-04-07 08:59 UTC, Smthng0 commented on src/main/java/com/losthex/App.java
> +            licenseManagerClass.activateAndCheckLicense(args[0], args[1], args[2], args[3], args[4]);
simplify this if/else with a String isStaging = ? args[4] : "no"

2023-04-07 08:59 UTC, Smthng0 commented on src/main/java/com/losthex/App.java
> +            System.out.println("Four arguments required: apiKey, sharedKey, licenceKey, productName and optional isStaging(yes/no) variable");
throw an exception here after logging it (invalid arguments exception or something similar)

2023-04-07 08:59 UTC, Smthng0 commented on src/test/java/com/losthex/AppTest.java
> +        assertTrue(true);
add a test that will check arguments length (if not 4 or 5 - assert that it throws the correct exception type)

and another test that throws error for random arguments

2023-04-07 11:38 UTC, fr33d00m approved these changes
@MIOCIC this looks slick. Great job. :)

FYI @Smthng0

2023-04-07 11:39 UTC, merged